### ISSUE TITLE
How to send some params

### ISSUE THREAD

**Issue by alekseychikin** [lzrski/atomic-rest#1]
For example i wanna send

```
{
  "firstname": "Aleksei",
  "age": 13
}
```

How will a request looks like?
I've tried like this:

```
{
  "hostname": "localhost",
  "path": "/users/add/",
  "method": "POST",
  "body": {
    "firstname": "Aleksei",
    "age": 13
  }
}
```

And like this:

```
{
  "hostname": "localhost",
  "path": "/users/add/",
  "method": "POST",
  "body": "firstname=Aleksei&age=13"
}
```

It doesn't works.

**Comment by tad-lispy** [comment]
Hi!

I'm pleased you tried it - I didn't expect anyone to do so :) It was my toy project to learn how to make Atom plugins.

Anyway, try this:

```
POST http://localhost/users/add/
  firstname: 'Aleksei'
  age: 13
```

ATM you have to select entire block before making the request. Then you should be able to send it with `alt-ctrl-enter`.

Please let me know if that helps.
