### ISSUE TITLE
JSON responses appear as [object Object]

### ISSUE THREAD

**Issue by jkellerer** [lzrski/atomic-rest#4]
Issue:
The provide output is not useful when calling a rest service that responds with content type "application/json". Body content is "[object Object]".

Reason: 
The type of the variable "body" is a JSON object tree (not String) when using the rest client to call a service that responds with content type "application/json" (JSON parsing is performed by the client prior to calling the callback). 
The current implementation however always expects it to be a String otherwise it will explicitly convert it using toString which is not providing useful results for Objects using the default toString implementation.

Example:

``` json
POST http://localhost:9200/apps/file/_search
{
    "query": {
        "range": {
            "file.size": {
                "to": 127543235
            }
        }
    }
}
```

```
### Response
# Headers:
{
  "content-type": "application/json; charset=UTF-8",
  "content-length": "5557"
}
# Body:
[object Object]
###
```

Changing

``` coffee
request {
      method
      url
      json
    }, (error, response, body) =>
      try body = cson.stringify JSON.parse(body), null, 2
      catch error
        console.log "Can't parse body as a JSON. Will show raw."
```

to

``` coffee
    request {
      method
      url
      json
    }, (error, response, body) =>
      try body = cson.stringify JSON.parse(body), null, 2
      catch error
        if body instanceof String
            console.log "Can't parse body as a JSON. Will show raw."
        else
            console.log "Body is a plain object, formatting it as CSON."
            body = cson.stringify body, null, 2
```

corrected this problem.

**Comment by tad-lispy** [comment]
Hi.

Frankly I can't reproduce it (I'm on Linux with Atom 0.190.0). Anyway I made a commit (a4de22e) in attempt to fix it. It's in the other branch now. Please take a look and let me know if it fixes the thing for you. If so, then I will merge it and make a new release tomorrow.

Thanks for taking an interest in this humble plugin. I'll be happy to get more issues and PRs from you in the future and also to make you a collaborator if you are interested in developing it further. There is definitely a lot to improve :)

**Comment by jkellerer** [comment]
Hi lzrski,

Thanks a lot for the quick action!

Just tried the branch, looks good. There's however one thing, the following code is triggered for object responses:

``` coffee
cson.stringify body
```

In difference to parsed responses this omits the pretty printing. I'm not sure if it makes sense though because no matter what the object is without pretty printing it will be harder to read. I'd suggest to add the same pretty printing as with parsed JSON responses.

Concerning reproduction of the problem: Looks like it depends on the HTTP method and whether there's a request body or not. 
E.g. using GET or POST against an es instance returns _body_ as string

```
GET http://localhost:9200/apps/file/_search
POST http://localhost:9200/apps/file/_search
```

Using POST with a JSON request body returns an object instead:

``` json
POST http://localhost:9200/apps/file/_search
{
    "query": {
        "range": {
            "file.size": {
                "to": 127543235
            }
        }
    }
}
```

**Comment by jkellerer** [comment]
Maybe I should add: Environment was: Atom 0.198.0 on OSX
